start_service_name: "start_capture" # Defines name suffix for std_srvs::Empty service which restarts suspended streaming
stop_service_name: "stop_capture"   # Defines name suffix for std_srvs::Empty service which suspends camera polling timer

video_device: /dev/video0           # Device driver's entrypoint
io_method: mmap                     # I/O method
                                    # - read - for devices supporting virtual filesystem or block I/O
                                    # - mmap - for devices with direct libusb memory mapping
                                    # - userptr - for userspace devices supporting userspace pointer exchange
pixel_format: yuyv                  # Pixel format for Video4linux device (also selects decoder mode)
                                        # https://wiki.videolan.org/YUV#YUV_4:2:0_.28I420.2FJ420.2FYV12.29
                                        # - yuyv - YUV420
                                        # - yuv - synonym for yuyv
                                        # - uyvy - UVY240
                                        # - yuvmono10 - Monochrome 10-bit pseudo-YUV
                                        # - rgb24 - Linear 8-bit RGB
                                        # - bgr24 - OpenCV-compatible 8-bit BGR
                                        # - grey - Grayscale 8-bit monochrome
                                        # - yu12 - YU-reversed YUV420
                                        # - mjpeg - FFMPEG decoder, MotionJPEG, for compatible hardware
                                        # - h264 - FFMPEG decoder, H.264, for compatible hardware
color_format: yuv422p               # On-chip color representation mode for the input frame encoded by hardware
                                        # - yuv422p - YUV422 - default, compatible with most MJPEG hardware encoders
                                        # - yuv420p - YUV420 - mandatory for H.264 and H.265 hardware encoders
create_suspended: false             # Instructs the node whether to start streaming immediately after launch
                                    # or to wait until the start service will be triggered
full_ffmpeg_log: false              # Allows to suppress warning messages generated by libavcodec, cleans log
camera_name: head_camera            # ROS internal name for the camera, used to generate camera_info message
camera_frame_id: head_camera        # Frame ID used to generate coordinate transformations
camera_transport_suffix: image_raw  # Suffix used by image_transport to generate topic names
camera_info_url: "package://usb_cam/config/head_camera0_2.yaml"                 # URI for camera calibration data (likely a YML file obtained from camera_calibration)
#camera_info_url: ""
image_width: 640                    # Frame dimensions, should be supported by camera hardware
image_height: 480
framerate: 30                       # Camera polling frequency, Hz (integer)

# Auxiliary camera parameters provided by libv4l2
    # Names for these parameters are generated automatically according to the intrinsic control names exported by the
    # camera driver. The node queries camera's kernel controller module to determine the parameters that can be set up
    # via ROS. For these parameters the corresponding ROS parameters with identical names are generated under this
    # namespace.
    # See also the comprehensive node output describing parameter names and feasible values for them to be set up here.
    # It is also possible to have a list of the available control names using v4l2-ctl application from v4l2-util package:
    # v4l2-ctl --device=/dev/video<ID> -L
intrinsic_controls:                 
    focus_auto: true
    exposure_auto_priority: true
    exposure_auto: 3
    white_balance_temperature_auto: true
    power_line_frequency: 1
    ignore: [
        brightness,
        contrast,
        saturation,
        gain,
        sharpness,
        backlight_compensation,
        white_balance_temperature,
        exposure_absolute,
        pan_absolute,
        tilt_absolute,
        focus_absolute,
        zoom_absolute
    ]                               # Use this list to enumerate the control names that should be delisted from the camera setup
                                    # NOTE: the ROS parameters for the V4L controls supported but listed here would be STILL
                                    # generated, but the values WILL NOT BE USED to set up the camera. To affect these controls
                                    # once you want to do that, their names should me REMOVED from this list!

# 用户控制
# 亮度 0x00980900（int）：最小值=-64 最大值=64 步长=1 默认=0 值=0
# 对比度 0x00980901（int）：最小值=0 最大值=64 步长=1 默认=32 值=32
# 饱和度0x00980902（int）：最小值= 0 最大值= 128 步长= 1 默认= 64 值= 64
# 色调 0x00980903（int）：最小值=-40 最大值=40 步长=1 默认=0 值=0
# white_balance_automatic 0x0098090c（布尔）：默认=1值=1
# 伽玛 0x00980910 (int) : 最小值=72 最大值=500 步长=1 默认=100 值=100
# 增益 0x00980913 (int) : 最小值=0 最大值=100 步长=1 默认=0 值=0
# power_line_freq 0x00980918（菜单）：最小值=0 最大值=2 默认=1 值=1
# 0：禁用
# 1：50赫兹
# 2：60赫兹
# 白平衡温度 0x0098091a（整数）：最小值=2800 最大值=6500 步骤=1 默认=4600 值=4600 标志=非活动
# 锐度 0x0098091b（int）：最小值=0 最大值=6 步长=1 默认=2 值=2
# 背光补偿 0x0098091c (int) : 最小值=0 最大值=2 步长=1 默认=1 值=1
# 相机控制
# 自动曝光 0x009a0901（菜单）：最小值=0 最大值=3 默认=3 值=3
# 1：手动模式
# 3：光圈优先模式
# Exposure_time_absolute 0x009a0902（int）：最小值=1 最大值=5000 步骤=1 默认=157 值=157 标志=非活动
# Exposure_dynamic_framerate 0x009a0903（布尔）：默认=0值=0